### ISSUE TITLE
Interpret IDE-helpers

### ISSUE THREAD

**Issue by ccondrup** [Gert-dev/php-integrator-linter#25]
First off, thanks for the awesome package(s), they help a lot. Not sure if I'm posting at correct place; I request this linter get support for interpreting ide-helpers like [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper/)

An example of a generated helper-file for Laravel 5.1: https://gist.github.com/barryvdh/5227822
Ref. this issue: https://github.com/barryvdh/laravel-ide-helper/issues/166

Linter reports:
![linter-prob](https://cloud.githubusercontent.com/assets/84788/14562205/a9cf1c28-031b-11e6-9cb0-bbd7285803fd.gif)
Currently the linter gives errors like these in a default Laravel 5.2 install. I did not get them on php 5.*, got them after switching to php 7x64. I'm on Win 10 x64, Atom 1.7-dev portable.

**Comment by ccondrup** [comment]
.. and ofc now it works, a couple minutes later. Seems I had to relaunch Atom and some files for the changes to take effect. Sorry, keep up the great work!

**Comment by Gert-dev** [comment]
No problem, glad to hear you managed to get it fixed!
