### ISSUE TITLE
Linter support for Symfony Annotations

### ISSUE THREAD

**Issue by najshot** [Gert-dev/php-integrator-linter#31]
Hello, I'd like to ask if there is a possibility to add annotation support for different Frameworks for Linter.
I use annotations in my Symfony projects and I get a lot of Warnings using Symfony Route or Template annotations:

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

Sensio\Bundle\FrameworkExtraBundle\Configuration\Route is not used anywhere.at line 10 col 5

Yet I use them just in annotations:
`
/**
 * @Route("somepath/somepath/somepath", name="somepath")
 * @Template()
 */`

Doctrine Annotations like
use Doctrine\ORM\Mapping as ORM;  
* @ORM\Table()
* @ORM\Entity 

Give me the same warning. Is there anything else I could use? or does this contend for a enchancment?.

btw. Thanks for your hard work, you make many of our lifes easier!

**Comment by Gert-dev** [comment]
Thanks for the compliment! There is unfortunately nothing else you can do at the moment, as this is indeed an enhancement (or even a bug) that I need to implement or resolve. The linting back end is not smart enough (yet) to pick up on the annotation tags, but it already knows which classes can be used as annotation via the `@Annotation` tag so this shouldn't be too hard to add.

**Comment by Gert-dev** [comment]
I had forgotten that I already put up a ticket about this on the base package [1]. I'll close this to keep the discussion centralized. Any further suggestions are of course, always welcome.

[1] https://github.com/Gert-dev/php-integrator-base/issues/166
