### ISSUE TITLE
Reports error when @ in PHP docs

### ISSUE THREAD

**Issue by UziTech** [Gert-dev/php-integrator-linter#33]
```php
/**
 * Validate email
 * @param string $email name@test.com
 * @return bool Valid email
 */
public function validateEmail($email) {
```

The above code gives the error "`The docblock for validateEmail is missing a @param tag for $email.`"

if I remove the `@` in the description of `$email` the error goes away

**Comment by Gert-dev** [comment]
This should be fixed now, feel free to reopen if this is not the case.
