### ISSUE TITLE
"boolean" was not found.

### ISSUE THREAD

**Issue by ricpelo** [Gert-dev/php-integrator-linter#35]
Linter complais about "boolean" data type in PHPDoc's @param.

![2016-06-18-171322_1280x1024_scrot](https://cloud.githubusercontent.com/assets/616169/16171763/43e036e2-3578-11e6-9076-06a9ab08e896.png)

**Comment by Gert-dev** [comment]
Not a bug, see also #30 and #28.

**Comment by ricpelo** [comment]
Great, thank you!

**Comment by Gert-dev** [comment]
You're welcome, thanks for taking the time to report issues!
