### ISSUE TITLE
COM was not found

### ISSUE THREAD

**Issue by UziTech** [Gert-dev/php-integrator-linter#37]
[COM](https://secure.php.net/manual/en/class.com.php) is not recognized as a built in class

**Comment by Gert-dev** [comment]
Does COM in lowercase letters work? It seems to actually be spelled as `com` when looking at `get_declared_classes`.

**Comment by UziTech** [comment]
Class and Function names are [case-**in**sensitive](http://stackoverflow.com/a/5643544/806777) in PHP. Maybe they need to be checked in a case-insensitive way

**Comment by Gert-dev** [comment]
They are, but I wanted to verify that that is indeed the issue (and not an indexing issue). Does it work when it's spelled in lower case?

**Comment by UziTech** [comment]
yes that works as expected
