### ISSUE TITLE
Error regarding unknown annotate

### ISSUE THREAD

**Issue by hultberg** [Gert-dev/php-integrator-linter#39]
Hello!

I'm using phpmd along with integrator linter. In a method I have the following annotate:
````
/**
 * @SuppressWarnings(PHPMD.ElseExpression)
 */
````

This is to suppress a phpmd warning, only to get another warning from php integrator linter. I would like the linter to accept this annotate.

![screen shot 2016-07-22 at 18 13 26](https://cloud.githubusercontent.com/assets/1257913/17063590/644e5320-5038-11e6-9548-4e8faf602013.png)

**Comment by Gert-dev** [comment]
This will be part of base package release 1.1.0.

**Comment by hultberg** [comment]
Closing this as the issue has been fixed.
