### ISSUE TITLE
Grouped `use`-statement not working

### ISSUE THREAD

**Issue by manulaiko** [Gert-dev/php-integrator-linter#40]
When using grouped `use`-statement like this:

    <?php
    namespace Foo;
    
    use \Bar\{
        A,
        B,
        C
    };

It doesn't recognizes them resulting in a lot of issues although they're working properly.

As an image is worth a thousand words:

![image](https://i.imgur.com/XoCPW5J.png "Grouped `use`-statement")

**Comment by Gert-dev** [comment]
Thanks for reporting this. Should be fixed with base package 1.1.2.
