### ISSUE TITLE
Question about user defined functions warning.

### ISSUE THREAD

**Issue by Gensoki** [Gert-dev/php-integrator-linter#42]
How would I avoid the "documentation for (function-name) is missing" warning?

**Comment by Gert-dev** [comment]
By adding the documentation ;-). For example, this will have a warning:

```php
function foo()
{

}
```

To solve it, you document the function:

```php
/**
 * Does foo.
 */
function foo()
{

}
```

For class methods, the warning will not show if it overrides a parent method that already has documentation.

Hope this helps!
