### ISSUE TITLE
Error whenever I type a character in PHP

### ISSUE THREAD

**Issue by spikeon** [Gert-dev/php-integrator-linter#45]
I am copying this from php-integrator-base, where I thought this issue was before I came up with a temporary solution. 

---

I'm getting a VERY annoying VERY unhelpful error whenever I type any character in a php file:

If you could tell me what this means and how to fix it... or at least get it to shut up... I'd appreciate it.

php-integrator - Oops, something went wrong!
PHP sent back something unexpected. This is most likely an issue with your setup. If you're sure this is a bug, feel free to report it on the bug tracker.

→ 0
100

-----

I got it to stop by uninstalling php-integrator-linter. Disabling it didn't help, I had to fully uninstall it.

**Comment by Gert-dev** [comment]
This seems to be an Atom issue, see also [1].

[1] https://github.com/Gert-dev/php-integrator-base/issues/213
